#Google Analytics
analytics-id: UA-157926257-1

#Subtitle
subtitle:
  active: false
  text: 

#Nav 
nav:
  pages:
    active: true
  social:
    active: true

#Featured images in homepage
featured-img:
  active: true

#Show categories at the end of posts
categories:
  active: false

#Show date and read time under the post title
date-under-post:
  active: true

#Use MathJAX
mathjax:
  active: true

#Show related posts based on categories
related-posts:
  active: false
  title: "You May Also Enjoy"

#Disqus
disqus:
  disqus_shortname: "alessio-franceschi-blog" #Your disqus shortname. Leave blank to deactivate disqus comments